[application]

# App (Project) Name
name = "Gamba"

# Dioxus App Default Platform
# desktop, web, mobile, ssr
default_platform = "web"

# `build` & `serve` dist path
out_dir = "dist"

[web.app]

# HTML title tag content
title = "Gamba | ⛺"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.watcher]
reload_html = true

watch_path = ["src", "assets", "public"]

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
