use axum::Json;
use serde_json::{json, Value};

use crate::util::errors::AppResult;

pub mod util;

// This file is generated by build.rs
include!(concat!(env!("OUT_DIR"), "/version.rs"));

pub async fn default_handler() -> AppResult<Json<Value>> {
    Ok(Json(json!({
        "name": "gamba (api)",
        "version": VERSION,
    })))
}
