name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "Dockerfile"
      - ".github/workflows/publish.yml"
      - "Cargo.toml"
      - "Cargo.lock"
      - "migrations/**"

jobs:
  publish:
    name: Publish Gamba image to container registries
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: true

      - name: Build the docker image
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: gamba:latest

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Slim the image
        uses: kitabisa/docker-slim-action@v1
        env:
          DSLIM_HTTP_PROBE: false
        with:
          target: gamba:latest
          tag: slim

      - name: Build and push Gamba Docker image
        uses: docker/build-push-action@c84f38281176d4c9cdb1626ffafcd6b3911b5d94 # tag=v3.1.1
        with:
          push: true
          context: .
          file: Dockerfile
          tags: ghcr.io/${{ github.GITHUB_REPOSITORY_OWNER }}/gamba:latest
