name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "Dockerfile"
      - ".github/workflows/publish.yml"
      - "Cargo.toml"
      - "Cargo.lock"
      - "migrations/**"

jobs:
  publish:
    name: Publish Gamba image to container registries
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: true

      - name: Build the docker image
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: gamba:{{github.run_number}}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Slim the image
        uses: kitabisa/docker-slim-action@v1
        env:
          DSLIM_HTTP_PROBE: false
        with:
          target: gamba:{{ github.run_number }}
          tag: "slim-{{ github.run_number }}"

      - name: Build and push Gamba Docker image
        uses: docker/build-push-action@1104d471370f9806843c095c1db02b5a90c5f8b6 # v3.3.1
        with:
          push: true
          context: .
          file: Dockerfile
          tags: ghcr.io/${{ github.GITHUB_REPOSITORY_OWNER }}/gamba:slim-${{ github.run_number }}
